name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - id: setup-firefox
        uses: browser-actions/setup-firefox@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel
      - name: Run tests
        run: |
          python3 -m unittest
        env:
          ACTIONS_FF_OVERRIDE: ${{ steps.setup-firefox.outputs.firefox-path }}/..
      - name: Geckodriver logs
        if: failure()
        run:
          cat geckodriver.log || true
        shell: bash
